export const typesGamesES = [
    'Nuevos',
    'De moda',
    'Actualizados',
    'Originals',
    '2 jugadores',
    'Acción',
    'Aventuras',
    'Baloncesto',
    'Belleza',
    'Billar',
    'Cartas',
    'Casual',
    'Clic',
    'Coches',
    'Conducir',
    'Controller',
    'Defensa de torres',
    'Deportes',
    'Disparos',
    'Escape',
    'First person shooter',
    'Flash',
    'Fútbol',
    '.io',
    'Mahjong',
    'Minecraft',
    'Motos',
    'Multijugador',
    'Puzzle',
    'Stickman',
    'Terror',
    'Vestir',
];

export const typesGamesEN = [
    'New',
    'Trending now',
    'Updated',
    'Originals',
    '2 Player',
    'Action',
    'Adventure',
    'Basketball',
    'Beauty',
    'Bike',
    'Car',
    'Card',
    'Casual',
    'Clicker',
    'Controller',
    'Dess Up',
    'Driving',
    'Escape',
    'Flash',
    'FPS',
    'Horror',
    '.io',
    'Mahjong',
    'Minecraft',
    'Multiplayer',
    'Pool',
    'Puzzle',
    'Shooting',
    'Soccer',
    'Sports',
    'Stickman',
    'Tower Defense',
];
