export const typesGamesES = [
    {
        name: 'Nuevos',
        svg: 'New.svg',
        path: 'new',
        genre: false,
    },
    {
        name: 'De moda',
        svg: 'Trending.svg',
        path: 'default',
        genre: false,
    },
    {
        name: 'Actualizados',
        svg: 'Updated.svg',
        path: 'significantly-updated',
        genre: false,
        // GetUrl Function
    },
    {
        name: '2 jugadores',
        svg: '2players.svg',
        path: '2-player',
        genre: true,
    },
    {
        name: 'Acción',
        svg: 'Action.svg',
        path: 'action',
        genre: true,
    },
    {
        name: 'Aventuras',
        svg: 'Adventure.svg',
        path: 'adventure',
        genre: true,
    },
    {
        name: 'Baloncesto',
        svg: 'Basketball.svg',
        path: 'basketball',
        genre: true,
    },
    {
        name: 'Belleza',
        svg: 'Beauty.svg',
        path: 'Beauty',
        genre: true,
    },
    {
        name: 'Billar',
        svg: 'Pool.svg',
        path: 'pool',
        genre: true,
    },
    {
        name: 'Cartas',
        svg: 'Card.svg',
        path: 'card',
        genre: true,
    },
    {
        name: 'Casual',
        svg: 'Casual.svg',
        path: 'casual',
        genre: true,
    },
    {
        name: 'Clic',
        svg: 'Clicker.svg',
        path: 'clicker',
        genre: true,
    },
    {
        name: 'Coches',
        svg: 'Car.svg',
        path: 'car',
        genre: true,
    },
    {
        name: 'Conducir',
        svg: 'Driving.svg',
        path: 'driving',
        genre: true,
    },
    {
        name: 'Controller',
        svg: 'Controller.svg',
        path: 'controller',
        genre: true,
    },
    {
        name: 'Defensa de torres',
        svg: 'TowerDefense.svg',
        path: 'tower-defense',
        genre: true,
    },
    {
        name: 'Deportes',
        svg: 'Sports.svg',
        path: 'sports',
        genre: true,
    },
    {
        name: 'Disparos',
        svg: 'Shooting.svg',
        path: 'shooting',
        genre: true,
    },
    {
        name: 'Escape',
        svg: 'Escape.svg',
        path: 'escape',
        genre: true,
    },
    {
        name: 'FPS',
        svg: 'FPS.svg',
        path: 'first-person-shooter',
        genre: true,
    },
    {
        name: 'Flash',
        svg: 'Flash.svg',
        path: 'flash',
        genre: true,
    },
    {
        name: 'Fútbol',
        svg: 'Soccer.svg',
        path: 'soccer',
        genre: true,
    },
    {
        name: '.io',
        svg: 'io.svg',
        path: 'io',
        genre: true,
    },
    {
        name: 'Mahjong',
        svg: 'Mahjong.svg',
        path: 'mahjong',
        genre: true,
    },
    {
        name: 'Minecraft',
        svg: 'Minecraft.svg',
        path: 'minecraft',
        genre: true,
    },
    {
        name: 'Motos',
        svg: 'Bike.svg',
        path: 'bike',
        genre: true,
    },
    {
        name: 'Multijugador',
        svg: 'Multiplayer.svg',
        path: 'multiplayer',
        genre: true,
    },
    {
        name: 'Puzzle',
        svg: 'Puzzle.svg',
        path: 'puzzle',
        genre: true,
    },
    {
        name: 'Stickman',
        svg: 'Stickman.svg',
        path: 'stickman',
        genre: true,
    },
    {
        name: 'Terror',
        svg: 'Horror.svg',
        path: 'horror',
        genre: true,
    },
    {
        name: 'Vestir',
        svg: 'DressUp.svg',
        path: 'dress-up',
        genre: true,
    },
];

export const typesGamesEN = [
    'New',
    'Trending',
    'Updated',
    'Originals',
    '2 Player',
    'Action',
    'Adventure',
    'Basketball',
    'Beauty',
    'Bike',
    'Car',
    'Card',
    'Casual',
    'Clicker',
    'Controller',
    'Dress Up',
    'Driving',
    'Escapedriving',
    'Flash',
    'FPS',
    'Horror',
    '.io',
    'Mahjong',
    'Minecraft',
    'Multiplayer',
    'Pool',
    'Puzzle',
    'Shooting',
    'Soccer',
    'Sports',
    'Stickman',
    'Tower Defense',
];
